import type { CatalogItem } from './types'

export const sampleCatalog: CatalogItem[] = [
  {
    id: 'frontend-design',
    slug: 'frontend-design',
    title: 'Frontend Design',
    type: 'Plugin',
    summary: 'Diretrizes de interface para acelerar padroes visuais e reduzir retrabalho em layouts.',
    ownContent: 'Aplique antes de iniciar uma nova entrega de interface para manter coerencia visual da equipe.',
    officialUrl: 'https://github.com/anthropics/claude-code',
    sourceUrls: ['https://github.com/anthropics/claude-code'],
    instructions: '/plugin install frontend-design@claude-plugins-official',
    status: 'published',
    visibility: 'team',
    category: 'Plugins',
    topics: ['frontend', 'design'],
    tags: ['ui', 'layout', 'interface'],
  },
  {
    id: 'context7',
    slug: 'context7',
    title: 'Context7',
    type: 'MCP',
    summary: 'Leva documentacao atualizada para o fluxo, reduzindo decisao baseada em memoria desatualizada.',
    ownContent: 'Use para reduzir exemplos e bibliotecas obsoletas durante implementacao.',
    officialUrl: 'https://github.com/upstash/context7',
    sourceUrls: ['https://github.com/upstash/context7'],
    instructions: 'npx @upstash/context7-mcp',
    status: 'published',
    visibility: 'team',
    category: 'MCPs',
    topics: ['documentacao'],
    tags: ['api', 'biblioteca', 'docs'],
  },
  {
    id: 'playwright',
    slug: 'playwright',
    title: 'Playwright MCP',
    type: 'MCP',
    summary: 'Valida fluxos reais no navegador para tomar decisoes com confiança antes de ir para producao.',
    ownContent: 'Use para testar telas, formularios e jornadas criticas com rastreabilidade.',
    officialUrl: 'https://github.com/microsoft/playwright-mcp',
    sourceUrls: ['https://github.com/microsoft/playwright-mcp'],
    instructions: 'claude mcp add playwright npx @playwright/mcp@latest',
    status: 'published',
    visibility: 'team',
    category: 'MCPs',
    topics: ['testes'],
    tags: ['browser', 'e2e', 'qa'],
  },
]
